version: '3'
volumes:
  mysql-data:
    driver: local

services:
  nginx:
    image: nginx
    container_name: "light-nginx"
    ports:
      - "${PORT}:80"
    volumes:
      - ./:/var/www/
      - ./server/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./server/docker/php
    container_name: "light-php"
    volumes:
      - ./:/var/www

  mysql:
    restart: always
    image: mysql:5.7
    container_name: "light-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASS}
      MYSQL_USER: ${DOCKER_DB_USERNAME}
      MYSQL_PASSWORD: ${DOCKER_DB_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_DB_DATABASE}
      MYSQL_TEST_DATABASE: ${DOCKER_TEST_DATABASE}
    ports:
      - 23306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./server/docker/mysql:/docker-entrypoint-initdb.d
