#!/bin/bash
heroku config:set --app ca-com DB_CONNECTION=mysql \
APP_ENV=production \
LOCALE=ja \
TIMEZONE="Asia/Tokyo" \
DB_HOST=us-cdbr-iron-east-02.cleardb.net \
DB_PORT=3306 \
DB_DATABASE=heroku_e7df1b836c186e6 \
DB_USERNAME=bf31f80e1986a7 \
DB_PASSWORD=0087f40a \
APP_URL=https://ca-com.herokuapp.com/ \
MAIL_DRIVER=ses \
MAIL_FROM_ADDRESS=service@ca-com.life \
MAIL_FROM_NAME=キャリアアドバイザー.com \
AWS_ACCESS_KEY_ID=AKIA4DAYXXHRMFW5ORF2 \
AWS_SECRET_ACCESS_KEY=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 \
AWS_REGION=ap-northeast-1 \
AWS_BUCKET=career-adviser-production \
SES_KEY=AKIA4DAYXXHRMFW5ORF2 \
SES_SECRET=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 \
SES_REGION=us-east-1 \
SLACK_CHANNEL=#notification \
SLACK_NAME=キャリアアドバイザー.com会員登録通知 \
SLACK_ICON=https://ca-com.herokuapp.com/favicon.ico \
SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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 \
TWITTER_CLIENT_ID=gnSU8fx0GCki9dxxp26GVRTWF \
TWITTER_CLIENT_SECRET=JOJIDNNmJAACIMvTuC83uXeNdjLcwIjBtZApZKWkPEWmWwviob \
CALLBACK_URL=https://reliable-bungotaketa-2752.lolipop.io/auth/twitter/callback
